### ISSUE TITLE
Cannot import Keras?

### ISSUE THREAD

**Issue by swertz** [cp3-llbb/HHTools#57]
I've tried setting up what is needed to evaluate the NNs trained with Keras. As explained in #52 the only thing that should be needed is to execute the small script in HHTools to register Keras with CMSSW.

However after doing that I cannot import keras in a python console. Since that is done in `common/KerasModelEvaluator.h`, I figured it should work...:
```
>>> import keras
Using TensorFlow backend.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nfs/scratch/fynu/sbrochet/Framework/CMSSW_8_0_24_patch1_HH_TensorFlow_build/install/keras/lib/python2.7/site-packages/keras/__init__.py", line 2, in <module>
    from . import backend
  File "/nfs/scratch/fynu/sbrochet/Framework/CMSSW_8_0_24_patch1_HH_TensorFlow_build/install/keras/lib/python2.7/site-packages/keras/backend/__init__.py", line 69, in <module>
    from .tensorflow_backend import *
  File "/nfs/scratch/fynu/sbrochet/Framework/CMSSW_8_0_24_patch1_HH_TensorFlow_build/install/keras/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 1, in <module>
    import tensorflow as tf
  File "/nfs/scratch/fynu/sbrochet/Framework/CMSSW_8_0_24_patch1_HH_TensorFlow_build/install/keras/lib/python2.7/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/nfs/scratch/fynu/sbrochet/Framework/CMSSW_8_0_24_patch1_HH_TensorFlow_build/install/keras/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 59, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/nfs/scratch/fynu/sbrochet/Framework/CMSSW_8_0_24_patch1_HH_TensorFlow_build/install/keras/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 53, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/nfs/scratch/fynu/sbrochet/Framework/CMSSW_8_0_24_patch1_HH_TensorFlow_build/install/keras/lib/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: No module named google.protobuf


Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.
```

Did I misunderstand the instructions?

**Comment by blinkseb** [comment]
Can you retry to import keras from a python shell? It should work now

**Comment by swertz** [comment]
It does, thanks a lot!

**Comment by blinkseb** [comment]
For the record, a dependency of tensorflow (protobuf) was not installed. It worked for me because I have this dependency already installed in my home folder...
